### ISSUE TITLE
Publishing role at ansible galaxy?

### ISSUE THREAD

**Issue by Mehonoshin** [mbaran0v/ansible-role-alertmanager-bot#4]
Hey, @mbaran0v!
Thank you for this repo.
What do you think about publishing the role at galaxy.ansible.com?

**Comment by mbaran0v** [comment]
Hi! Ok, i publish role https://galaxy.ansible.com/mbaran0v/ansible_role_alertmanager_bot
By the way, you can import role directly from gihutb. For example:
```
$ cat requirements.yml
---

- name: mbaran0v.alertmanager-bot
  path: vendor/roles
  src: https://github.com/mbaran0v/ansible-role-alertmanager-bot.git
  version: 1.1.1

```

**Comment by Mehonoshin** [comment]
Thank you. Yes, I did imported it from GitHub, but I believe having it at ansible galaxy is nice to have, usually I use it to search for roles.
